fix for the vtable problem, you need to implement correctly the first virtual fonction ( as declared ) in the list, to have the pointer to the vtable...
Other function will return undefined reference to the correct function-name if not defined, not the first one.

BTW : you should never inline virtual function if you want something portable, because some compiler might have a weird behaviour on those...